language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

sudo: false

cache:
  directories:
    - $HOME/wheelhouse

env:
  - WHEELHOUSE=$HOME/wheelhouse/`python --version`

install:
  - pip wheel --find-links=$HOME/wheelhouse --wheel-dir=$HOME/wheelhouse . httpretty pytest flake8 ordereddict
  - pip install --find-links=$HOME/wheelhouse --no-index . httpretty pytest flake8 ordereddict

script:
  - flake8 .
  - py.test -v
